//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitleType
    {
        public TitleType()
        {
            this.Title = new HashSet<Title>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Title> Title { get; set; }
    }
}
