//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> episodes { get; set; }
        public string imageUrl { get; set; }
        public Nullable<int> titleType { get; set; }
    
        public virtual TitleType TitleType1 { get; set; }
        public virtual UserLists UserLists { get; set; }
    }
}
