//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLists
    {
        public int listType { get; set; }
        public int idTitle { get; set; }
        public Nullable<int> episodes { get; set; }
    
        public virtual ListType ListType1 { get; set; }
        public virtual Title Title { get; set; }
    }
}
